<a href="https://colab.research.google.com/github/AmjadaAshraf/data_science/blob/master/co1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def concate_string(string1,string2):
  return string1+string2
str1=input("String 1: ")
str2=input("String 2: ")
str3=concate_string(str1,str2)
print("String after concatination : ",str3)

String 1: amj
String 2: ada
String after concatination :  amjada


In [ ]:
def fibonacci_recursion(n):
    if n<=0:
      return 0
    if n==1:
      return 1
    else :
      return (fibonacci_recursion(n-1)+fibonacci_recursion(n-2))
n=int(input("enter n : "))
if n<=0:
  print("enter the number of terms!!!")
else :
  print("fibonacci sequance")
  for i in range(n):
    print(fibonacci_recursion(i))

enter n : 5
fibonacci sequance
0
1
1
2
3


In [ ]:
def addition(a,b):
  return a+b
n1=int(input("number 1: "))
n2=int(input("number 2: "))
addition(n1,n2)

number 1: 12
number 2: 56


68

In [ ]:

addition(10,20)

30

In [ ]:
import datetime
#date=datetime.date.today()
time=datetime.datetime.now()
print(time)

2021-11-22 05:16:05.500230


In [ ]:
year=int(input("enter a year: "))
if (year%4)==0 and (year%100)!=0 :
    print("Leap year")
else :
    print("Not leap year")

enter a year: 2021
Not leap year


In [ ]:
class student :
  rollno=input("Roll no : ")
  name=input("Name : ")
  tot_mark=int(input("Total mark : "))
print("\nStudent Details:-")
print("Roll No : ",student.rollno)
print("Name : ",student.name)
print("Total Mark : ",student.tot_mark)

Roll no : A09606
Name : Arya Dayal
Total mark : 560

Student Details:-
Roll No :  A09606
Name :  Arya Dayal
Total Mark :  560


In [ ]:
class Rectangle :
  length=10
  breadth=20
  def rectangle_area(l,b):
    return l*b
  def rectangle_perimeter(l,b):
    return (2*(l+b))
print("Length : ",Rectangle.length)
print("Breadth : ",Rectangle.breadth)
print("Area of rectangle : ",Rectangle.rectangle_area(Rectangle.length,Rectangle.breadth))
print("Perimeter of rectangle :",Rectangle.rectangle_perimeter(Rectangle.length,Rectangle.breadth))

Length :  10
Breadth :  20
Area of rectangle :  200
Perimeter of rectangle : 60


In [ ]:
class Rect:
  def __init__(self,l,b):
    self.l=l
    self.b=b
  def display(self):
    area=self.l*self.b
    perimeter=2*(self.l+self.b)
    print("length:",self.l)
    print("breadth:",self.b)
    print("area:",area)
    print("perimeter:",perimeter)
obj1=Rect(10,20)
obj2=Rect(5,4)
obj1.display()
obj2.display()


length: 10
breadth: 20
area: 200
perimeter: 60
length: 5
breadth: 4
area: 20
perimeter: 18


In [ ]:
dict1={}
dict1[1]="Ant"
dict1[3]="Cat"
dict1[2]="Bear"
dict1[5]="Elephant"
dict1[4]="Dog"
dict1[6]="fox"
for i in sorted(dict1):
  print(i,dict1[i])

1 Ant
2 Bear
3 Cat
4 Dog
5 Elephant
6 fox


In [ ]:
class Operations:
  def __init__(self,n1,n2):
    self.n1=n1
    self.n2=n2
  def add(self,n1,n2):
    return self.n1+self.n2
  def sub(self,n1,n2):
    return self.n1-self.n2
  def mul(self,n1,n2):
    return self.n1*self.n2
  def div(self,n1,n2):
    return self.n1/self.n2
  def mod(self,n1,n2):
    return self.n1%self.n2
n1=int(input("number1: "))
n2=int(input("number2: "))
obj1=Operations(n1,n2)
print(n1,"+",n2," ",obj1.add(n1,n2))
print(n1,"-",n2," ",obj1.sub(n1,n2))
print(n1,"*",n2," ",obj1.mul(n1,n2))
print(n1,"/",n2," ",obj1.div(n1,n2))
print(n1,"%",n2," ",obj1.mod(n1,n2))

number1: 4
number2: 2
4 + 2   6
4 - 2   2
4 * 2   8
4 / 2   2.0
4 % 2   0


In [ ]:
a=int(input("number 1: "))
b=int(input("number 2: "))
try:
  res=a/b
  print(a,"/",b," ",res)
except:
  print()


In [ ]:
x=[[1,2,3],[5,6,7]]
res=[[0,0],[0,0],[0,0]]
for i in range(len(x)):
  for j in range(len(x[0])):
    res[j][i]=x[i][j]
for r in res:
  print(r)

[1, 5]
[2, 6]
[3, 7]


In [ ]:
import numpy as np
 
#Creating a matrix A
A = np.array([[3,4,3],[1,2,3],[4,2,1]])
 
#Performing SVD
U, sigma , V = np.linalg.svd(A)

print("matrix U :\n",U)
print("matrix sigma :\n",sigma)
print("matrix VT :\n",V)
#Checking if we can remake the original matrix using U,D,VT
A_remake = (U @ np.diag(sigma) @ V)
print("Remaked Matrix :\n",A_remake)

matrix U :
 [[-0.73553325 -0.18392937 -0.65204358]
 [-0.42657919 -0.62196982  0.65664582]
 [-0.52632788  0.76113306  0.37901904]]
matrix sigma :
 [7.87764972 2.54031671 0.69958986]
matrix VT :
 [[-0.60151068 -0.61540527 -0.5093734 ]
 [ 0.73643349 -0.18005275 -0.65210944]
 [ 0.30959751 -0.76737042  0.5615087 ]]
Remaked Matrix :
 [[3. 4. 3.]
 [1. 2. 3.]
 [4. 2. 1.]]


In [ ]:
x=[[1,2,3],[5,6,7]]
print(np.transpose(x))

[[1 5]
 [2 6]
 [3 7]]
